# Generated by Django 3.2.9 on 2021-12-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211216_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fulfilment',
        ),
    ]
